//
//  RootTabView.swift
//  MyTrack
//

import SwiftUI
import OSLog
import SwiftData

struct RootTabView: View {
    private enum RootTab: Hashable {
        case record
        case trips
        case reports
    }

    @Environment(\.modelContext) private var modelContext
    @Environment(AppServices.self) private var appServices
    @Environment(\.scenePhase) private var scenePhase
    @Query private var allReports: [GeneratedReport]
    @State private var selectedTab: RootTab = .record
    @State private var isPendingReviewPresented = false
    @State private var isGeneratingPeriodicReports = false

    /// Drives the badge on the Rapports tab. Filtered in Swift rather than in
    /// the query so the same `allReports` fetch stays reusable, and because the
    /// number of reports is small by nature.
    private var unopenedReportCount: Int {
        allReports.filter { $0.openedAt == nil }.count
    }

    var body: some View {
        TabView(selection: $selectedTab) {
            Tab("Enregistrer", systemImage: "record.circle", value: RootTab.record) {
                RecordTripView()
            }
            Tab("Trajets", systemImage: "list.bullet", value: RootTab.trips) {
                TripListView()
            }
            Tab("Rapports", systemImage: "doc.text", value: RootTab.reports) {
                ReportsView()
            }
            .badge(unopenedReportCount)
        }
        .onAppear {
            if hasPendingTrips {
                isPendingReviewPresented = true
            }
            // A notification tapped on a cold launch is handled by the delegate
            // before this view is ever on screen, so the flags have to be
            // checked here too and not only in onChange.
            openReportsTabIfRequested()
            presentPendingReviewIfRequested()
            // Deliberately a plain Task rather than .task: report generation
            // must not be cancelled by leaving the tab, or a PDF could be
            // written with no matching record ever created for it.
            Task { await generatePeriodicReportsIfDue() }
        }
        .sheet(isPresented: $isPendingReviewPresented) {
            PendingTripsReviewView()
        }
        // Handled once here, at the tab root, rather than in a per-tab
        // listener: TabView keeps every tab alive, so the same flag would
        // otherwise be consumed several times over.
        .onChange(of: appServices.notificationService.shouldOpenReportsTab) { _, _ in
            openReportsTabIfRequested()
        }
        .onChange(of: appServices.notificationService.shouldOpenPendingTripsReview) { _, _ in
            presentPendingReviewIfRequested()
        }
        // A report coming due while the app merely sits in the background used
        // to wait for the next cold launch — which on a daily-use app can be
        // weeks away. The user would tap "your report is ready", land on the
        // Rapports tab and find nothing there. Launch can reach this too, on
        // the .inactive -> .active transition, so it may run alongside the
        // onAppear call; generatePeriodicReportsIfDue guards against that.
        .onChange(of: scenePhase) { _, newPhase in
            guard newPhase == .active else { return }
            Task { await generatePeriodicReportsIfDue() }
            // Motion & Fitness can be granted from the Settings app, which
            // CoreMotion reports to nobody. Coming back is the only moment the
            // app can notice, and start watching for drives at last.
            appServices.drivingDetector.refresh()
        }
    }

    private var hasPendingTrips: Bool {
        let descriptor = FetchDescriptor<Trip>()
        return ((try? modelContext.fetch(descriptor)) ?? [])
            .contains { $0.confirmationStatus == .pendingConfirmation }
    }

    /// Opens the review screen after the user taps a "did you make this trip?"
    /// notification. Checked against the trips actually waiting: the tapped
    /// trip may already have been resolved from the notification's own
    /// actions, and a review screen with nothing to review only traps them.
    private func presentPendingReviewIfRequested() {
        guard appServices.notificationService.shouldOpenPendingTripsReview else { return }
        appServices.notificationService.shouldOpenPendingTripsReview = false
        isPendingReviewPresented = hasPendingTrips
    }

    /// Brings the user to the Rapports tab after they tap a "your report is
    /// ready" notification. The report they were told about is generated by
    /// `generatePeriodicReportsIfDue` on this same launch and shows up at the
    /// top of the list, unopened, as soon as it exists.
    private func openReportsTabIfRequested() {
        guard appServices.notificationService.shouldOpenReportsTab else { return }
        selectedTab = .reports
        appServices.notificationService.shouldOpenReportsTab = false
    }

    /// Bounded so that a due date corrupted into the distant past can't spin
    /// generating reports forever.
    private static let maxCatchUpReportsPerProfile = 24

    /// Checks every periodic report profile independently, generating one report per
    /// period that came due — not just one per launch, so reopening the app after a
    /// long gap doesn't take several launches to produce the reports that were missed
    /// meanwhile. A profile that fails is left alone and simply retried next launch,
    /// without affecting the others.
    private func generatePeriodicReportsIfDue() async {
        // Launch and the first foreground transition can both ask for this at
        // once. Two runs racing on the same profile would each see the period
        // as still due — nextDueDate only advances once generation finishes —
        // and produce the same report twice.
        guard !isGeneratingPeriodicReports else { return }
        isGeneratingPeriodicReports = true
        defer { isGeneratingPeriodicReports = false }

        for profile in appServices.reportProfileService.allProfiles(in: modelContext) {
            var generatedCount = 0
            while generatedCount < Self.maxCatchUpReportsPerProfile,
                  let period = appServices.reportProfileService.periodDueForGeneration(profile: profile, now: .now) {
                guard await generateReport(for: profile, over: period) else { break }
                generatedCount += 1
            }
        }
    }

    /// Returns false when generation failed, leaving `nextDueDate` untouched on
    /// purpose so the period is retried rather than skipped.
    private func generateReport(
        for profile: ReportProfile,
        over period: (periodStart: Date, periodEnd: Date)
    ) async -> Bool {
        let periodStart = period.periodStart
        let periodEnd = period.periodEnd
        let descriptor = FetchDescriptor<Trip>(
            predicate: #Predicate { $0.startDate >= periodStart && $0.startDate < periodEnd }
        )
        var tripsInPeriod = (try? modelContext.fetch(descriptor)) ?? []
        if !profile.vehicles.isEmpty {
            let vehicleIDs = Set(profile.vehicles.map(\.persistentModelID))
            tripsInPeriod = tripsInPeriod.filter { trip in
                guard let vehicle = trip.vehicle else { return false }
                return vehicleIDs.contains(vehicle.persistentModelID)
            }
        }
        let confirmedTrips = tripsInPeriod.filter { $0.confirmationStatus == .confirmed }
        // Trips still awaiting an answer can't be counted, but their absence
        // has to be visible: the report is a document of record, and this
        // period is never generated again once nextDueDate moves on.
        let pendingTripCount = tripsInPeriod.filter { $0.confirmationStatus == .pendingConfirmation }.count

        do {
            _ = try await appServices.reportGenerationService.generateReport(
                trips: confirmedTrips,
                periodStart: periodStart,
                periodEnd: periodEnd,
                source: .periodic,
                profileName: profile.name,
                includedVehicles: profile.vehicles,
                pendingTripCount: pendingTripCount,
                in: modelContext
            )
        } catch {
            AppLog.reports.error(
                "Periodic report failed for \(profile.name, privacy: .public): \(error.localizedDescription, privacy: .public)"
            )
            return false
        }

        if let newDueDate = appServices.reportProfileService.advanceAfterGeneration(
            profile: profile, generatedThrough: periodEnd, in: modelContext
        ) {
            appServices.notificationService.scheduleReportReadyNotification(
                for: newDueDate, profileID: profile.id, profileName: profile.name
            )
        }
        return true
    }
}

#Preview {
    let container = try! ModelContainer(
        for: Trip.self, Vehicle.self, UserProfile.self, ReportProfile.self, GeneratedReport.self,
        configurations: ModelConfiguration(isStoredInMemoryOnly: true)
    )
    return RootTabView()
        .environment(AppServices(modelContext: container.mainContext))
        .modelContainer(container)
}
